import {
  MAINNET,
  MAINNET__CONTRACT_ADDRESS,
  MAINNET__RPC_FULL_URL,
  MAINNET__SMALL_INTERACTION_COST_APPROX,
  TESTNET__CONTRACT_ADDRESS,
  TESTNET__RPC_FULL_URL,
  TESTNET__SMALL_INTERACTION_COST_APPROX,
} from 'react-native-dotenv';

export const SMALL_INTERACTION_COST_APPROX =
  MAINNET === 'true'
    ? MAINNET__SMALL_INTERACTION_COST_APPROX
    : TESTNET__SMALL_INTERACTION_COST_APPROX;

export const RPC_FULL_URL =
  MAINNET === 'true' ? MAINNET__RPC_FULL_URL : TESTNET__RPC_FULL_URL;

export const CONTRACT_ADDRESS =
  MAINNET === 'true' ? MAINNET__CONTRACT_ADDRESS : TESTNET__CONTRACT_ADDRESS;
