---
version: "2.0"

services:
  validate-purchase-ios:
    image: sturmenta/validate-purchase-ios:latest
    env:
      - MAIN_MNEMONIC=<copy-from-.env>
      - BTTC_RPC_API_KEY=<copy-from-.env>
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
profiles:
  compute:
    validate-purchase-ios:
      resources:
        cpu:
          units: 0.25
        memory:
          size: 128Mi
        storage:
          size: 128Mi
  placement:
    akash:
      pricing:
        validate-purchase-ios:
          denom: uakt
          amount: 10000
deployment:
  validate-purchase-ios:
    akash:
      profile: validate-purchase-ios
      count: 2
