const MAINNET__RPC_FULL_URL = process.env.MAINNET__RPC_FULL_URL
const TESTNET__RPC_FULL_URL = process.env.TESTNET__RPC_FULL_URL

const MAINNET__ETHERSCAN_ADDRESS_URL =
  process.env.MAINNET__ETHERSCAN_ADDRESS_URL
const TESTNET__ETHERSCAN_ADDRESS_URL =
  process.env.TESTNET__ETHERSCAN_ADDRESS_URL

// ────────────────────────────────────────────────────────────────────────────────

const RPC_FULL_URL = (MAINNET) =>
  MAINNET ? MAINNET__RPC_FULL_URL : TESTNET__RPC_FULL_URL

const ETHERSCAN_ADDRESS_URL = (MAINNET) =>
  MAINNET ? MAINNET__ETHERSCAN_ADDRESS_URL : TESTNET__ETHERSCAN_ADDRESS_URL

module.exports = {
  PRIVATE_KEY,
  RPC_FULL_URL,
  ETHERSCAN_ADDRESS_URL,
}
